### ISSUE TITLE
Awesome work!!!

### ISSUE THREAD

**Issue by artknight** [dartilesm/alexgit#21]
### What did you come up with? What is your idea?

Hey, I wasn’t sure how to reach you, so I’m posting here. I love your work and decided to feature your library in my daily tech newsletter, https://dailysandbox.com

### AlexGit version

0.0.1

### Environment

- OS: MacOS
- Terminal: zsh

**Comment by dartilesm** [comment]
Hey @artknight, thank you for that!! Appreciate it
